version: '3.8'

services:
  db:
    image: postgres:14.6-alpine
    container_name: app_container
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      -  ./postgres:/var/lib/postgresql/data
